### PR TITLE
Check if filesystem supports extended attributes

### PR DESCRIPTION
**Pull request by kuba--**

### CODE REVIEW

**Comment by rfjakob** [comment]
Good idea!

But I think you need something like https://github.com/rfjakob/gocryptfs/blob/db778aae7db844e77b602816a4fd0aeab5d6857e/internal/fusefrontend/xattr.go#L147

At the moment the `== ENOTSUPP` comparision does not work:
```
$ go test -v
=== RUN   Test
--- FAIL: Test (0.00s)
	xattr_test.go:89: xattr.Set /tmp/208921818 user.test: operation not supported
=== RUN   TestNoData
--- FAIL: TestNoData (0.00s)
	xattr_test.go:89: xattr.Set /tmp/525488753 user.test: operation not supported
FAIL
exit status 1
FAIL	github.com/pkg/xattr	0.002s
```

**Comment by kuba--** [comment]
In `syscalls` we have two errors related to _operation is not supported_:
- `syscall.ENOTSUP`
- `syscall.EOPNOTSUPP`

apart from _no supported protocol or socket_, so I've added extra check for `EOPNOTSUPP`

**Comment by rfjakob** [comment]
A comparison between xattr.Error and syscall.Errno is always false!

```sh
0 jakob@brikett:~/go/src/github.com/pkg/xattr$ git describe --tags
v0.2.3-2-g8ce696a

0 jakob@brikett:~/go/src/github.com/pkg/xattr$ go test -v
=== RUN   Test
--- FAIL: Test (0.00s)
	xattr_test.go:86: xattr.Set /tmp/526248302 user.test: operation not supported
=== RUN   TestNoData
--- FAIL: TestNoData (0.00s)
	xattr_test.go:86: xattr.Set /tmp/852740085 user.test: operation not supported
FAIL
exit status 1
FAIL	github.com/pkg/xattr	0.002s
```

**Comment by rfjakob** [comment]
Maybe something like this?
```go
	err2 := err.(*xattr.Error)
	if err2.Err == syscall.EOPNOTSUPP {
		// do something
	}
```

**Comment by kuba--** [comment]
I think it should be sth. like:
```
err2.Err == syscall.Errno(syscall.ENOTSUP) || err2.Err == syscall.Errno(syscall.EOPNOTSUPP)
```

**Comment by rfjakob** [comment]
Double cast

https://github.com/golang/go/blob/dc3a92edaabf012cabd90304bac1ed8fe3bb7444/src/syscall/zerrors_linux_amd64.go#L1302
```
	ENOTSUP         = Errno(0x5f)
	EOPNOTSUPP      = Errno(0x5f)
```

**Comment by kuba--** [comment]
On darwin `ENOTSUP` and `EOPNOTSUPP` have different values

**Comment by rfjakob** [comment]
Wow!
```
	EOPNOTSUPP      = Errno(0x66)
	ENOTSUP         = Errno(0x2d)
```

**Comment by kuba--** [comment]
@rfjakob does following implementation, works for you?
```go
func checkIfError(t *testing.T, err error) {
	if err == nil {
		return
	}

	errno := err.(*Error)
	if errno == nil {
		t.Fatal(err)
	}

	// check if filesystem supports extended attributes
	if errno.Err == syscall.Errno(syscall.ENOTSUP) || errno.Err == syscall.Errno(syscall.EOPNOTSUPP) {
		t.Skip("Skipping test - filesystem does not support extended attributes")
	} else {
		t.Fatal(err)
	}
}
```

**Comment by rfjakob** [comment]
Yes, works:
```
$ go test -v
=== RUN   Test
--- SKIP: Test (0.00s)
	xattr_test.go:89: Skipping test - filesystem does not support extended attributes
=== RUN   TestNoData
--- SKIP: TestNoData (0.00s)
	xattr_test.go:89: Skipping test - filesystem does not support extended attributes
PASS
ok  	github.com/pkg/xattr	0.002s
```

**Pull request merged**
